# Generated by Django 4.2.6 on 2023-10-26 20:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBF_DATE_LAST_UPDATE', models.DateField()),
                ('OBJECTID', models.IntegerField()),
                ('rfb_distri', models.CharField(max_length=12)),
                ('ID', models.IntegerField()),
                ('AREA', models.FloatField()),
                ('PERIMETER', models.FloatField()),
                ('CFB_TYPE', models.CharField(max_length=4)),
                ('CFB_CODE', models.IntegerField()),
                ('LAKE_TYPE', models.CharField(max_length=8)),
                ('Shape_Area', models.FloatField()),
                ('Shape_Length', models.FloatField()),
                ('OS_LAYER', models.CharField(max_length=9)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'National Lake',
                'verbose_name_plural': 'National Lakes',
            },
        ),
    ]
