# Generated by Django 4.2.6 on 2023-10-26 21:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('rfb_distri', models.CharField(max_length=12)),
                ('custom_id', models.IntegerField()),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('cfb_type', models.CharField(max_length=4)),
                ('cfb_code', models.IntegerField()),
                ('lake_type', models.CharField(max_length=8)),
                ('shape_area', models.FloatField()),
                ('shape_len', models.FloatField()),
                ('os_layer', models.CharField(max_length=9)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Lake',
                'verbose_name_plural': 'Lakes',
            },
        ),
        migrations.DeleteModel(
            name='NationalLake',
        ),
    ]
