# Generated by Django 4.2.6 on 2023-10-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_lakes_delete_nationallake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lakes',
            old_name='area',
            new_name='AREA',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='cfb_code',
            new_name='CFB_CODE',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='cfb_type',
            new_name='CFB_TYPE',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='custom_id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='lake_type',
            new_name='LAKE_TYPE',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='objectid',
            new_name='OBJECTID',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='os_layer',
            new_name='OS_LAYER',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='perimeter',
            new_name='PERIMETER',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='shape_area',
            new_name='Shape_Are',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='shape_len',
            new_name='Shape_Len',
        ),
    ]
