# Generated by Django 4.2.6 on 2023-10-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_rename_area_lakes_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lakes',
            name='OBJECTID',
        ),
    ]
