# Generated by Django 4.2.6 on 2023-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_remove_lakes_objectid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lakes',
            options={},
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='AREA',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='CFB_CODE',
            new_name='cfb_code',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='CFB_TYPE',
            new_name='cfb_type',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='LAKE_TYPE',
            new_name='lake_type',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='ID',
            new_name='objectid',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='OS_LAYER',
            new_name='os_layer',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='PERIMETER',
            new_name='perimeter',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='Shape_Are',
            new_name='shape_are',
        ),
        migrations.RenameField(
            model_name='lakes',
            old_name='Shape_Len',
            new_name='shape_len',
        ),
        migrations.AlterField(
            model_name='lakes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
