# Generated by Django 4.2.6 on 2023-10-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_alter_lakes_options_rename_area_lakes_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakes',
            name='os_layer',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
