# Generated by Django 4.2.6 on 2023-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_alter_lakes_os_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
