# Generated by Django 4.2.6 on 2023-10-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0009_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
